TITLE = 'sphinxcontrib-lpblocks'
SUMMARY = 'Literate Programming with reStructuredText'
URL = 'https://github.com/rblack42/sphinxcontrib-lpblocks'
PYPI = 'http://pypi.python.org/pypi/sphinxcontrib-lpblocks'
AUTHOR = 'Roie R. Black'
EMAIL = 'roie.black@gmail.com'
LICENSE = 'BSD 3-Clause'
